### ISSUE TITLE
Incomplete finish pass

### ISSUE THREAD

**Issue by johnsonm** [fenrus75/FenrusCNCtools#3]
From [twitter](https://twitter.com/mcdanlj/status/1345545196214300673)...

Making github happy by putting it in a zip file: [rhodonea-5-7-2.2-18.zip](https://github.com/fenrus75/FenrusCNCtools/files/5761126/rhodonea-5-7-2.2-18.zip)

Happy to provide any other files that might be useful. Here's the stl2nc settings:

![image](https://user-images.githubusercontent.com/79751/103470851-d82f6900-4d45-11eb-8f28-181ad7fd6eb7.png)

**Comment by fenrus75** [comment]
ok reproduced the issue; now debugging.
On first look, it looks like the zigzagging for the raster does not start far enough out

**Comment by fenrus75** [comment]
one bug found and fixed (double negative sigh) checking if there's others

**Comment by fenrus75** [comment]
ok small tweak for slightly finger first cut line ... but this is fixed for me now, I just pushed the fixes

thanks for the report (interesitng I never noticed this before... it started off by about a radius, and I usually use R=0.5mm bits)

**Comment by johnsonm** [comment]
Indeed, that looks much better! ☺
